### ISSUE TITLE
Support the use of bconds

### ISSUE THREAD

**Issue by hroncok** [sclorg/rpm-list-builder#70]
Once the syntax is established in https://github.com/sclorg/rhscl-rebuild-recipes/issues/25 implement a support for [bcond conditionals](http://rpm.org/user_doc/conditional_builds.html).

**Comment by hroncok** [comment]
It is possible to use this for the time being:

```yaml
    - python3:
        macros:
          _without_rewheel: 1
```
